### PR TITLE
Add saber from fate/stay night

### LINKED ISSUE #2: [Fumo Request] Saber from fate/stay night
It's vital for me.
изображение

### PR DESCRIPTION
**Pull request by rautyrauty**
The model was made in the Blender.

Closes: https://github.com/upsidedownsweetfood/FumoPlushiesMT/issues/2

### CODE REVIEW

**Comment by rautyrauty** [comment]
изображение

**Comment by upsidedownsweetfood** [comment]
Thanks a lot for the contribution, looks so cute

**Comment by rautyrauty** [comment]
@upsidedownsweetfood the commit has been deleted from main

**Comment by rautyrauty** [comment]
изображение

**Comment by upsidedownsweetfood** [comment]
oh my, My fault, Can you redo a pull-request?

**Comment by rautyrauty** [comment]
No, I won't do that, because it won't look very nice in the history of the github project.
I didn't delete my branch, merge it yourself.

**Pull request merged**
